### ISSUE TITLE
屏幕调用

### ISSUE THREAD

**Issue by hunanghuan03** [WU-CVGL/DreamMesh4D#1]
![微信图片_20241014231251](https://github.com/user-attachments/assets/fb4e28b1-800d-4b57-b605-67702f18cc4f)
作者您好！我在进行# mesh export这一步的时候出现了这样的报错。因为我是租用的远程主机，所以没有屏幕，请问这个问题您有思路嘛？谢谢您~

**Comment by lizhiqi49** [comment]
You can change the "context_type" argument of exporter from "gl" to "cuda", in the config file.
